# Start with the Alpine 3.19 Docker image.
FROM alpine:3.19

# Install libc6-compat, required for executables generated by FPC.
RUN apk --no-cache add libc6-compat
# Install sqlite-libs to support [catDB,catMemDB,catPermMemDB] cache types.
RUN apk --no-cache add sqlite-libs

# Set working directory in the container image.
WORKDIR /app

# Copy the YTuner files from host into container image.
COPY bin/ /app/
COPY share/ /app/host-shared/
 
# Make the TCP/UDP ports to outside the container.
EXPOSE 80/tcp
EXPOSE 53/udp

RUN mkdir -p /app/host-shared/{db,cache}
RUN chmod 777 -R /app/host-shared/
RUN chmod +x /app/ytuner
# Run YTuner.
CMD ["./ytuner"]
