Dance:
  Vanilla Radio: https://stream.vanillaradio.com:8090/live|https://www.vanillaradio.com/wp-content/uploads/2016/04/vanilla-logo-300x100.png
  FFH - Eurodance: http://mp3.ffh.de/ffhchannels/hqeurodance.mp3|https://static.ffh.de/fileadmin/fm-dam/ffh.de/pages/musik/webradios/nologo/ffh_eurodance_nologo_600x600.jpg
  Splash 90s Dance: https://c6.auracast.net/radio/8090/radio.mp3|https://www.splashradio.eu/assets/images/emisoras/accb98123d7d32ee76fe126f725a2d3c.jpg
  Coco und Jambo: https://stream.laut.fm/cocoundjambo|https://d3kle7qwymxpcy.cloudfront.net/images/broadcasts/32/02/124749/1/c175.png
  Radio 90s Eurodance: https://listen1.myradio24.com/5967
  
Pop Music:
  Antenne Bayern: http://stream.antenne.de/antenne/stream/mp3|https://www.antenne.de/logos/antenne-bayern/apple-touch-icon.png
  Sky Radio 101 FM: http://22723.live.streamtheworld.com/SKYRADIO.mp3|https://www.skyradio.nl/icons/apple-icon.png
  538 Radio: http://23603.live.streamtheworld.com/RADIO538_SC|https://www.538.nl/icons/apple-icon.png

Rock:
  Radio Beat 95.3 FM: http://icecast5.play.cz/radiobeat128.mp3|https://www.radiobeat.cz/img/logo.png
  RockFM 101.6: http://rockfm-cope-rrcast.flumotion.com/cope/rockfm-low.mp3
  4U Classic Rock: https://str4uice.streamakaci.com/4uclassicrock.mp3|https://cdn.onlineradiobox.com/img/l/4/15394.v1.png
